n= input('Digite algo: ')
print(f'O tipo primitivo deese valor é {type(n)}')
print(f'So tem espaço? {n.isspace()}')
print(f'É um número? {n.isnumeric()}')
print('É alfabetico? {}'.format(n.isalpha()))
print('É alfanumerica? {}'.format(n.isalnum()))
print(f'Está em maiusculas? {n.isupper()}')
print('Está em minusculas? {}'.format(n.isupper()))
print('Está capitalizada? {}'.format(n.istitle()))